In [1]:
import numpy as np

In [2]:
data = np.loadtxt('./Sales.csv',delimiter = ',', skiprows = 1)
print(data)

[[  1. 120.  90.  60.]
 [  2. 130. 100.  65.]
 [  3. 125.  95.  70.]
 [  4. 140. 110.  75.]
 [  5. 150. 115.  80.]]


In [3]:
Total_sales_ProductA = np.sum(data[:,1])
Total_sales_ProductB= np.sum(data[:,2])
Total_sales_ProductC= np.sum(data[:,3])
print(Total_sales_ProductA,Total_sales_ProductB,Total_sales_ProductC)

665.0 510.0 350.0


In [4]:
Daily_total_sales = np.sum(data[:,1:],axis=1)
print(Daily_total_sales)

[270. 295. 290. 325. 345.]


In [5]:
Avg_sales_ProductA = np.average(data[:,1])
Avg_sales_ProductB = np.average(data[:,2])
Avg_sales_ProductC = np.average(data[:,3])
print(Avg_sales_ProductA,Avg_sales_ProductB,Avg_sales_ProductC)

133.0 102.0 70.0


In [6]:
Best_Selling = max(Total_sales_ProductA,Total_sales_ProductB,Total_sales_ProductC)
print(Best_Selling)

665.0


In [7]:
Worst_day = min(Daily_total_sales)
print(Worst_day)

270.0


In [8]:
Daily_growth = np.diff(Daily_total_sales)
print(Daily_growth)

[25. -5. 35. 20.]


In [9]:
Sales_Decreasing_Days = [idx+1 for idx,val in enumerate(Daily_growth) if val<0]
print(Sales_Decreasing_Days)

[2]


In [10]:
# ((today-yesterday)/(yesterday))*100 formula for daily_growth_percentage
Growth_Percentage_ProductA = ((data[1:,1] - data[:4,1])/data[:4,1])*100
Growth_Percentage_ProductB = ((data[1:,2] - data[:4,2])/data[:4,2])*100
Growth_Percentage_ProductC = ((data[1:,3] - data[:4,2])/data[:4,3])*100
print(Growth_Percentage_ProductA)
print(Growth_Percentage_ProductB)
print(Growth_Percentage_ProductC)

[ 8.33333333 -3.84615385 12.          7.14285714]
[11.11111111 -5.         15.78947368  4.54545455]
[-41.66666667 -46.15384615 -28.57142857 -40.        ]


In [11]:
Prediction_For_Next_Day = np.average(Daily_total_sales)
print(Prediction_For_Next_Day)

305.0


In [12]:
Sales_Performance = ['High Sales' if x>(np.average(Daily_total_sales)) else 'Low Sales' for x in Daily_total_sales]
print(Sales_Performance)

['Low Sales', 'Low Sales', 'Low Sales', 'High Sales', 'High Sales']
